import streamlit as st
import pandas as pd
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

# ============================================================================
# PAGE CONFIGURATION
# ============================================================================
st.set_page_config(
    page_title="Deep Scouting - Anomaly Detection",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# LOAD DATA
# ============================================================================
@st.cache_data
def load_data():
    """Loads the final results generated by the backend."""
    # Ensure you have saved df_final_anomalies as a CSV from your notebook!
    try:
        df_anomalies = pd.read_csv("resources/anomalies_per_pos_AE.csv")
    except FileNotFoundError:
        # Temporary mockup in case the file doesn't exist yet
        st.error("File 'anomalies_per_pos_AE.csv' not found. Make sure to export the data from your Notebook.")
        df_anomalies = pd.DataFrame()
    
    return df_anomalies

# ============================================================================
# MAIN APP
# ============================================================================
def main():
    st.title("🤖 Deep Player Embeddings - Anomaly Detection")
    
    # Load data
    df_anomalies = load_data()
    
    # Sidebar navigation
    st.sidebar.header("Navigation")
    page = st.sidebar.radio("Select Section", ["Overview", "Deep Anomaly Hub"])
    
# ========================================================================
    # PAGE 1: OVERVIEW
    # ========================================================================
    if page == "Overview":
        st.header("Deep Autoencoder Overview")
        
        # Inserimento del Goal del progetto
        # Inserimento del Goal del progetto espanso
        st.info("""
        **🎯 Task Goal: Uncovering Tactical Innovators through Deep Learning**
        
        The primary objective of this advanced model is to move beyond traditional statistics by leveraging neural networks to automate the discovery of unique playing profiles. Specifically, this tool is designed to:
        
        * **Define the Standard (Tactical DNA):** Compress over 100 performance and physical metrics to learn the quintessential baseline profile for every macro-position across Europe.
        * **Detect Structural Anomalies:** Identify players whose playing style fundamentally breaks the traditional rules of their nominal role. We are not just looking for the *best* players, but for true *tactical outliers*—for example, a center-back who orchestrates play like a deep-lying playmaker, or a fullback with the attacking footprint of a winger.
        * **Drive Actionable Scouting:** Translate complex multidimensional mathematics (latent space deviations) into highly readable, real-world percentiles. This empowers sporting directors and analysts to discover unpredictable game-changers, tactical innovators, and highly versatile hybrid profiles that opponents struggle to counter.
        """)
        with st.expander("🧩 What is an Autoencoder for Anomaly Detection?", expanded=False):
            st.markdown("""
            An **Autoencoder** is a type of Feedforward Neural Network designed to learn a compressed representation of data. 
            We use it here to define the "standard tactical DNA" of a player and spot those who break the mold.
            
            ### How It Works:
            1. **Encoder (Compression)**: The network takes a player's full statistical profile (~115 features) and compresses it through hidden layers into a small "bottleneck" layer (down to 4-8 dimensions).
            2. **Bottleneck (Latent Space)**: This is the core "DNA". To fit the data here, the model is forced to learn the most important, non-linear relationships between stats (e.g., how high possession correlates with passing accuracy).
            3. **Decoder (Reconstruction)**: The network attempts to rebuild the original 115 features from the compressed bottleneck.
            4. **The Catch (Anomaly Detection)**: The model is trained to minimize the **Reconstruction Error** for the average player. If a player is a tactical anomaly (e.g., a CB with playmaker stats), the model won't know how to reconstruct their profile from the bottleneck. Their reconstruction error will spike, flagging them as an outlier!
            """)
        
        with st.expander("🛠️ How We Built This Advanced Model", expanded=False):
            st.markdown("""
            ### Data Preparation:
            - **Position-Specific Isolation**: We train a *separate* autoencoder for each macro-position (e.g., Wingers, Center Backs). This prevents the model from flagging a Winger as an anomaly just because they don't defend like a Center Back.
            - **Robust Scaling**: We applied a `QuantileTransformer(output_distribution='normal')` locally for each position. This handles extreme outliers during training and forces the stats into a clean, normal distribution.
            
            ### Dynamic Neural Architecture:
            To prevent overfitting, the network depth dynamically adjusts based on the amount of available data per position:
            - **High Volume (>250 players)**: Deep network (32 ➔ 16 ➔ **8 (Bottleneck)** ➔ 16 ➔ 32) with 20% Dropout.
            - **Medium Volume (100-250 players)**: Moderate network (24 ➔ **6 (Bottleneck)** ➔ 24) with 20% Dropout.
            - **Low Volume (<100 players)**: Shallow network (12 ➔ **4 (Bottleneck)** ➔ 12) to avoid memorizing small datasets.
            
            ### Training Specifications:
            - **Loss Function**: `Huber Loss`. Huber loss is robust to outliers, meaning the autoencoder learns the *true* average player profile without being skewed by the very anomalies we are trying to detect.
            """)
            
        with st.expander("📊 Interpreting the Anomaly Scores", expanded=False):
            st.markdown("""
            ### The Robust Anomaly Score (MAD)
            Instead of standard deviation (which gets skewed by extreme outliers), we use the **Median Absolute Deviation (MAD)**. 
            - We calculate the median reconstruction error for a position.
            - We measure how far players deviate from this median using MAD.
            - Any player with a **Robust Anomaly Score > 2.5** is officially classified as a "True Anomaly".
            
            ### Unpacking the "Why": Feature Deviations
            Finding an anomaly is only half the battle. To provide actionable scouting intelligence, we calculate the difference between the player's *actual* stats and the model's *reconstructed* stats using an **Inverse Transform** to show real-world metrics:
            - **Top Positive Deviations (📈)**: The raw stats where the player vastly exceeds what is expected for their specific role.
            - **Top Negative Deviations (📉)**: The typical positional traits this player completely ignores.
            """)
            
    # ========================================================================
    # PAGE 2: DEEP ANOMALY HUB
    # ========================================================================
    elif page == "Cluster Explorer":
        st.header("Deep Anomaly Hub")

if __name__ == "__main__":
    main()